# This configuration file is in TOML format.
# 
# Installation guide: https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide

[http]
port = 5001
#forcesslport = 5002 
#cert = "selfcert/cert.pem"
#key = "selfcert/key.pem"

[database]
type = "mariadb"
connection = "documize:documize@tcp(mariadb:3306)/documize"
salt = "tsu3Acndky8cdTNx3"

[install]
location = "selfhost"